"""
PID Autonomous Navigation
=========================

End-to-end demonstration of the autonomous navigation system.

Pipeline:
    A* Path Planning
        ↓
    Waypoint Generation
        ↓
    PID Heading Control
        ↓
    Differential-Drive Robot
        ↓
    Obstacle-Aware Navigation

This script demonstrates the final navigation result.
Detailed experiments are available in the experiments/ directory.
"""

import numpy as np
import matplotlib.pyplot as plt

from controllers.heading_controller import HeadingController
from vehicle.differential_drive import DifferentialDriveRobot


# ============================================================
# Simulation Configuration
# ============================================================

DT = 0.01
SIMULATION_TIME = 15.0

ROBOT_SPEED = 1.0
WHEEL_BASE = 0.5

KP = 8.0
KI = 0.2
KD = 0.2

WAYPOINT_TOLERANCE = 0.10

START = (0.0, 0.0)
GOAL = (6.0, 5.0)


# ============================================================
# Demonstration Waypoints
#
# These represent the simplified path generated by the
# obstacle-aware planning stage.
# ============================================================

WAYPOINTS = np.array([
    [0.0, 0.0],
    [1.0, 1.0],
    [2.5, 2.5],
    [3.0, 3.0],
    [3.6, 3.0],
    [4.0, 3.2],
    [4.7, 3.9],
    [5.2, 4.3],
    [6.0, 5.0],
])


# ============================================================
# Robot and Controller
# ============================================================

robot = DifferentialDriveRobot(
    wheel_base=WHEEL_BASE,
    x=START[0],
    y=START[1],
    theta=0.0
)

heading_controller = HeadingController(
    kp=KP,
    ki=KI,
    kd=KD
)


# ============================================================
# Simulation Data
# ============================================================

time = np.arange(
    0,
    SIMULATION_TIME,
    DT
)

x_history = []
y_history = []
theta_history = []
heading_error_history = []

current_waypoint_index = 1
waypoint_reach_times = []


# ============================================================
# Main Simulation Loop
# ============================================================

for current_time in time:

    # --------------------------------------------------------
    # Check whether all waypoints have been reached
    # --------------------------------------------------------

    if current_waypoint_index >= len(WAYPOINTS):

        v_left = 0.0
        v_right = 0.0

        robot.update(
            v_left,
            v_right,
            DT
        )

        x_history.append(robot.x)
        y_history.append(robot.y)
        theta_history.append(robot.theta)
        heading_error_history.append(0.0)

        continue

    # --------------------------------------------------------
    # Current waypoint
    # --------------------------------------------------------

    target_x, target_y = WAYPOINTS[
        current_waypoint_index
    ]

    distance = np.sqrt(
        (target_x - robot.x) ** 2
        +
        (target_y - robot.y) ** 2
    )

    # --------------------------------------------------------
    # Waypoint reached
    # --------------------------------------------------------

    if distance <= WAYPOINT_TOLERANCE:

        waypoint_reach_times.append(
            current_time
        )

        current_waypoint_index += 1

        continue

    # --------------------------------------------------------
    # Desired heading
    # --------------------------------------------------------

    desired_heading = np.arctan2(
        target_y - robot.y,
        target_x - robot.x
    )

    # --------------------------------------------------------
    # PID heading control
    # --------------------------------------------------------

    angular_velocity = heading_controller.update(
        desired_heading,
        robot.theta,
        DT
    )

    # Limit angular velocity
    angular_velocity = np.clip(
        angular_velocity,
        -2.0,
        2.0
    )

    # --------------------------------------------------------
    # Reduce speed near waypoint
    # --------------------------------------------------------

    if distance < 0.5:

        linear_velocity = (
            ROBOT_SPEED
            * distance
            / 0.5
        )

        linear_velocity = max(
            linear_velocity,
            0.10
        )

    else:

        linear_velocity = ROBOT_SPEED

    # --------------------------------------------------------
    # Differential-drive conversion
    # --------------------------------------------------------

    v_left = (
        linear_velocity
        -
        angular_velocity
        * WHEEL_BASE
        / 2
    )

    v_right = (
        linear_velocity
        +
        angular_velocity
        * WHEEL_BASE
        / 2
    )

    # --------------------------------------------------------
    # Wheel velocity limits
    # --------------------------------------------------------

    MAX_WHEEL_SPEED = 1.5

    v_left = np.clip(
        v_left,
        -MAX_WHEEL_SPEED,
        MAX_WHEEL_SPEED
    )

    v_right = np.clip(
        v_right,
        -MAX_WHEEL_SPEED,
        MAX_WHEEL_SPEED
    )

    # --------------------------------------------------------
    # Update robot
    # --------------------------------------------------------

    robot.update(
        v_left,
        v_right,
        DT
    )

    # --------------------------------------------------------
    # Store data
    # --------------------------------------------------------

    x_history.append(robot.x)
    y_history.append(robot.y)
    theta_history.append(robot.theta)

    heading_error = heading_controller.normalize_angle(
        desired_heading - robot.theta
    )

    heading_error_history.append(
        np.rad2deg(heading_error)
    )


# ============================================================
# Final Performance
# ============================================================

final_x = robot.x
final_y = robot.y

final_distance = np.sqrt(
    (GOAL[0] - final_x) ** 2
    +
    (GOAL[1] - final_y) ** 2
)

all_waypoints_reached = (
    current_waypoint_index >= len(WAYPOINTS)
)


# ============================================================
# Console Summary
# ============================================================

print()
print("PID Autonomous Navigation")
print("=========================")

print(
    f"Start position: "
    f"({START[0]:.2f}, {START[1]:.2f}) m"
)

print(
    f"Goal position:  "
    f"({GOAL[0]:.2f}, {GOAL[1]:.2f}) m"
)

print(
    f"Final position: "
    f"({final_x:.2f}, {final_y:.2f}) m"
)

print(
    f"Final distance: "
    f"{final_distance:.3f} m"
)

print(
    f"PID gains: "
    f"Kp={KP}, Ki={KI}, Kd={KD}"
)

print(
    f"Waypoints reached: "
    f"{max(0, current_waypoint_index - 1)}"
    f"/{len(WAYPOINTS) - 1}"
)

if all_waypoints_reached:

    print(
        "Navigation status: "
        "SUCCESS"
    )

else:

    print(
        "Navigation status: "
        "INCOMPLETE"
    )


# ============================================================
# Plot Final Navigation
# ============================================================

plt.figure(
    figsize=(10, 8)
)

plt.plot(
    x_history,
    y_history,
    linewidth=2,
    label="Robot trajectory"
)

plt.plot(
    WAYPOINTS[:, 0],
    WAYPOINTS[:, 1],
    linestyle="--",
    linewidth=1.5,
    label="Planned path"
)

plt.scatter(
    START[0],
    START[1],
    s=100,
    label="Start"
)

plt.scatter(
    GOAL[0],
    GOAL[1],
    s=150,
    marker="*",
    label="Goal"
)

plt.scatter(
    WAYPOINTS[1:, 0],
    WAYPOINTS[1:, 1],
    s=60,
    label="Tracking waypoints"
)

plt.xlabel(
    "X position (m)"
)

plt.ylabel(
    "Y position (m)"
)

plt.title(
    "PID Autonomous Navigation"
)

plt.axis("equal")

plt.grid(True)

plt.legend()

plt.tight_layout()

plt.show()


# ============================================================
# Plot Heading Error
# ============================================================

plt.figure(
    figsize=(10, 5)
)

plt.plot(
    time[:len(heading_error_history)],
    heading_error_history,
    linewidth=2
)

plt.axhline(
    0,
    linestyle="--"
)

plt.xlabel(
    "Time (s)"
)

plt.ylabel(
    "Heading error (degrees)"
)

plt.title(
    "Navigation Heading Tracking Error"
)

plt.grid(True)

plt.tight_layout()

plt.show()